### ISSUE TITLE
Update package.json to reflect the move

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/go-multiaddr-fmt#3]
It currently references github.com/whyrusleeping/mafmt

**Comment by hsanjuan** [comment]
Then import path will need to be updated on all dependencies that use this.

**Comment by raulk** [comment]
Was fixed in https://github.com/multiformats/go-multiaddr-fmt/commit/08b1b5ee0f52f2f4300fed26fc3e145d89b5de4e.
